### User Creation
POST http://localhost:5000/user/new-user HTTP/1.1
Content-Type: application/json

{
    "username": "Navaneeth",
    "email": "nava@gmail.com",
    "password": "1234nava"
}

### User Login
POST http://localhost:5000/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "Navaneeth",
    "password": "1234nava"
}

### Admin Login
POST http://localhost:5000/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "password": "akmnt12345"
}

### User protected Route test
GET http://localhost:5000/user/protected HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpYXQiOjE3MTExMjY4NTIsImV4cCI6MTcxMTIxMzI1Mn0.jRT0NYc1BCoukrHDLe8EAVzm1JxzyBIxnPgv5yoXltc

### Campaign Test
GET http://localhost:5000/campaign/campaign HTTP/1.1

### All Active Campaigns
GET http://localhost:5000/campaign/campaigns HTTP/1.1

### Campaign Creation
POST http://localhost:5000/campaign/new-campaign HTTP/1.1
Content-Type: application/json

{
    "campaignTitle": "HeartSurgeryFunding",
    "firstName": "Madhumitha",
    "lastName": "Hatti",
    "age": 20,
    "gender": "female",
    "mobileNumber": 8919224476,
    "email": "hattimadhumitha@gmail.com",
    "bloodGroup": "AB+",
    "hospitalName": "Yasodha",
    "hospitalAddress" :"Hi-TechCity,Hyderabad,Telangana",
    "patientRoomNo": 203,
    "fundsRequired": 500000,
    "fundingDeadline": "24-03-2024",
    "verified": false,
    "completed": false,
    "id": 191713865017007,
    "fundsRaised": 0
}