### User Creation
POST http://localhost:5000/user/new-user HTTP/1.1
Content-Type: application/json

{
    "username": "Navaneeth",
    "email": "nava@gmail.com",
    "password": "1234nava"
}

### User Login
POST http://localhost:5000/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "Navaneeth",
    "password": "1234nava"
}

### Admin Login
POST http://localhost:5000/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "password": "akmnt12345"
}

### Campaign Test
GET http://localhost:5000/campaign HTTP/1.1

### Campaign Creation
POST http://localhost:5000/campaign/new-campaign HTTP/1.1
Content-Type: application/json

{
    "campaignTitle":"HeartSurgeryFunding",
    "firstName":"Madhumitha",
    "lastName":"Hatti",
    "age":20,
    "gender":"female",
    "mobileNumber":8919224476,
    "email":"hattimadhumitha@gmail.com",
    "bloodGroup":"AB+",
    "hospitalName":"Yasodha",
    "hospitalAddress":"Hi-TechCity,Hyderabad,Telangana",
    "patientRoomNo":203,
    "fundRequired":"500000",
    "fundingDeadline":"24-03-2024",
    "verification":"false",
    "completed":"false",
    "id":"23-03-2024"
}