### Test
GET http://localhost:5000/ HTTP/1.1

### User Test
GET http://localhost:5000/user HTTP/1.1

### User Creation
POST http://localhost:5000/user/new-user HTTP/1.1
Content-Type: application/json

{
    "username": "Navaneeth",
    "email": "nava@gmail.com",
    "password": "1234nava"
}